services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: mission_control
      POSTGRES_USER: mission
      POSTGRES_PASSWORD: control
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
